// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnFFW6mSihT04eIHPnuLvYDayA6gpCydI',
    appId: '1:822389878377:web:c320b26c3834b0a1133cf8',
    messagingSenderId: '822389878377',
    projectId: 'auvnet-ecommerce-22521',
    authDomain: 'auvnet-ecommerce-22521.firebaseapp.com',
    storageBucket: 'auvnet-ecommerce-22521.firebasestorage.app',
    measurementId: 'G-BN4RKR84GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8RuOldffMO3bsNhsYj0QNh4fmGoKqa0o',
    appId: '1:822389878377:android:cdc21a03ef48aaa3133cf8',
    messagingSenderId: '822389878377',
    projectId: 'auvnet-ecommerce-22521',
    storageBucket: 'auvnet-ecommerce-22521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzaGkC64gxPHZ9NUe53j56iljiRu7ciLI',
    appId: '1:822389878377:ios:8058b43a04b4008f133cf8',
    messagingSenderId: '822389878377',
    projectId: 'auvnet-ecommerce-22521',
    storageBucket: 'auvnet-ecommerce-22521.firebasestorage.app',
    iosBundleId: 'com.example.auvnetEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzaGkC64gxPHZ9NUe53j56iljiRu7ciLI',
    appId: '1:822389878377:ios:8058b43a04b4008f133cf8',
    messagingSenderId: '822389878377',
    projectId: 'auvnet-ecommerce-22521',
    storageBucket: 'auvnet-ecommerce-22521.firebasestorage.app',
    iosBundleId: 'com.example.auvnetEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnFFW6mSihT04eIHPnuLvYDayA6gpCydI',
    appId: '1:822389878377:web:494bf0fdf12d12ae133cf8',
    messagingSenderId: '822389878377',
    projectId: 'auvnet-ecommerce-22521',
    authDomain: 'auvnet-ecommerce-22521.firebaseapp.com',
    storageBucket: 'auvnet-ecommerce-22521.firebasestorage.app',
    measurementId: 'G-W1PK7LS198',
  );
}
